export const wordsToEnglish = {
    "zanahoria": "carrot",
    "papa": "potato",
    "patata": "potato",
    "cebolla": "onion",
    "ajo": "garlic",
    "lechuga": "lettuce",
    "espinaca": "spinach",
    "brócoli": "broccoli",
    "pepino": "cucumber",
    "tomate": "tomato",
    "pimiento": "pepper",
    "pimiento rojo": "red pepper",
    "pimiento verde": "green pepper",
    "calabacín": "zucchini",
    "berenjena": "eggplant",
    "coliflor": "cauliflower",
    "repollo": "cabbage",
    "champiñón": "mushroom",
    "seta": "mushroom",
    "maíz": "corn",
    "apio": "celery",
    "nabo": "turnip",
    "remolacha": "beet",
    "alcachofa": "artichoke",
    "rábano": "radish",
    "calabaza": "pumpkin",
    "guisantes": "peas",
    "habas": "broad beans",
    "cebollino": "chives",
    "escarola": "escarole",
    "endivia": "endive",
    "rúcula": "arugula",
    "judía verde": "green bean",
    "okra": "okra",
    "hinojo": "fennel",
    "manzana": "apple",
    "plátano": "banana",
    "platano": "banana",
    "banana": "banana",
    "naranja": "orange",
    "pera": "pear",
    "uva": "grape",
    "uva verde": "green grape",
    "uva roja": "red grape",
    "sandía": "watermelon",
    "melón": "melon",
    "piña": "pineapple",
    "fresa": "strawberry",
    "frambuesa": "raspberry",
    "arándano": "blueberry",
    "arándano rojo": "cranberry",
    "limón": "lemon",
    "lima": "lime",
    "mango": "mango",
    "papaya": "papaya",
    "durazno": "peach",
    "melocotón": "peach",
    "cereza": "cherry",
    "granada": "pomegranate",
    "kiwi": "kiwi",
    "coco": "coconut",
    "agua": "drops",
    "aguacate": "avocado",
    "higo": "fig",
    "atun": "tuna",
    "atún": "tuna",
    "salmón": "salmon",
    "trucha": "trout",
    "bacalao": "cod",
    "merluza": "hake",
    "sardina": "sardine",
    "anchoa": "anchovy",
    "langosta": "lobster",
    "camarón": "shrimp",
    "gamba": "prawn",
    "mejillón": "mussel",
    "almeja": "clam",
    "ostra": "oyster",
    "calamar": "squid",
    "pulpo": "octopus",
    "carne de res": "beef",
    "ternera": "veal",
    "cerdo": "pork",
    "pollo": "chicken",
    "pavo": "turkey",
    "cordero": "lamb",
    "ciruela": "plum",
    "mandarina": "mandarin",
    "maracuyá": "passion fruit",
    "guayaba": "guava",
    "lichi": "lychee",
    "tamarindo": "tamarind",
    "caqui": "persimmon",
    "arroz": "rice",
    "frijoles": "beans",
    "judías": "beans",
    "garbanzos": "chickpeas",
    "lentejas": "lentils",
    "harina": "flour",
    "azúcar": "sugar",
    "sal": "salt",
    "aceite": "oil",
    "aceite de oliva": "olive oil",
    "aceite vegetal": "vegetable oil",
    "vinagre": "vinegar",
    "miel": "honey",
    "café": "coffee",
    "té": "tea",
    "cacao": "cocoa",
    "atún": "tuna",
    "sardinas": "sardines",
    "sopa": "soup",
    "tomate enlatado": "canned tomato",
    "maíz enlatado": "canned corn",
    "chiles enlatados": "canned chiles",
    "conservas": "preserves",
    "pasta": "pasta",
    "fideos": "noodles",
    "sémola": "semolina",
    "avena": "oats",
    "pan rallado": "breadcrumbs",
    "levadura": "yeast",
    "bicarbonato": "baking soda",
    "almidón": "starch",
    "leche": "milk",
    "leche en polvo": "powdered milk",
    "queso": "cheese",
    "mantequilla": "butter",
    "yogur": "yogurt",
    "huevo": "egg",
    "huevos": "eggs",
    "nata": "cream",
    "queso crema": "cream cheese",
    "leche condensada": "condensed milk",
    "nuez": "nut",
    "nueces": "nuts",
    "almendra": "almond",
    "avellana": "hazelnut",
    "cacahuate": "peanut",
    "maní": "peanut",
    "pistacho": "pistachio",
    "nuez de macadamia": "macadamia",
    "nuez de brasil": "brazil nut",
    "anacardo": "cashew",
    "semillas de girasol": "sunflower seeds",
    "semillas de calabaza": "pumpkin seeds",
    "semillas de chía": "chia seeds",
    "semillas de lino": "flax seeds",
    "sésamo": "sesame",
    "ajonjolí": "sesame",
    "trigo": "wheat",
    "maíz": "corn",
    "cebada": "barley",
    "centeno": "rye",
    "avena": "oats",
    "arroz integral": "brown rice",
    "arroz blanco": "white rice",
    "harina": "flour",
    "harina de maíz": "corn flour",
    "harina de avena": "oat flour",
    "harina integral": "whole wheat flour",
    "alcachofa": "artichoke",
    "berro": "watercress",
    "brotes de soja": "bean sprouts",
    "col rizada": "kale",
    "coles de bruselas": "brussels sprouts",
    "endibia": "endive",
    "hinojo": "fennel",
    "jengibre": "ginger",
    "laurel": "bay leaf",
    "mostaza": "mustard (plant)",
    "perejil": "parsley",
    "romero": "rosemary",
    "sábila": "aloe vera",
    "salvia": "sage",
    "tomillo": "thyme",
    "wasabi": "wasabi",
    "cebolla roja": "red onion",
    "chalota": "shallot",
    "arándano silvestre": "wild blueberry",
"ciruela pasa": "prune",
"guayaba": "guava",
"jackfruit": "jackfruit",
"jocote": "hog plum",
"longan": "longan",
"mora": "blackberry",
"níspero": "loquat",
"pitahaya": "dragon fruit",
"rambután": "rambutan",
"tamarindo": "tamarind",
"uva pasa": "raisin",
"yaca": "jackfruit",
"alforfón": "buckwheat",
"amaranto": "amaranth",
"arroz basmati": "basmati rice",
"arroz jazmín": "jasmine rice",
"ceci": "chickpea",
"chícharos": "peas",
"mijo": "millet",
"quinoa": "quinoa",
"trigo sarraceno": "buckwheat",
"soja": "soybean",
"tapioca": "tapioca",
"teff": "teff",
"cacahuate": "peanut",
"guisante": "pea",
"lupino": "lupin",
"nuez moscada": "nutmeg",
"pistacho": "pistachio",
"semillas de amapola": "poppy seeds",
"semillas de cáñamo": "hemp seeds",
"aceitunas": "olives",
"ají": "chili pepper",
"alcaparras": "capers",
"azafrán": "saffron",
"canela": "cinnamon",
"clavo": "clove",
"comino": "cumin",
"curry": "curry",
"curcuma": "turmeric",
"extracto de vainilla": "vanilla extract",
"mostaza": "mustard",
"pimienta negra": "black pepper",
"pimentón": "paprika",
"sal marina": "sea salt",
"salsa de soja": "soy sauce",
"salsa picante": "hot sauce",
"vinagre balsámico": "balsamic vinegar",
"vinagre de manzana": "apple cider vinegar",
"arándano": "blueberry",
"ciruela": "plum",
"guayaba": "guava",
"jackfruit": "jackfruit",
"jocote": "hogplum",
"longan": "longan",
"mora": "blackberry",
"níspero": "loquat",
"pitahaya": "dragonfruit",
"rambután": "rambutan",
"tamarindo": "tamarind",
"uva": "grape",
"yaca": "jackfruit",
"mandarina": "mandarin",
"higo": "fig",
"caqui": "persimmon",
"coco": "coconut",
"kiwi": "kiwi",
"alforfón": "buckwheat",
"amaranto": "amaranth",
"ceci": "chickpea",
"chícharo": "pea",
"mijo": "millet",
"quinoa": "quinoa",
"soja": "soybean",
"tapioca": "tapioca",
"teff": "teff",
"lenteja": "lentil",
"garbanzo": "chickpea",
"frijol": "bean",
"nuez": "nut",
"almendra": "almond",
"avellana": "hazelnut",
"cacahuate": "peanut",
"maní": "peanut",
"pistacho": "pistachio",
"anacardo": "cashew",
"poppy": "amapola",
"sésamo": "sesame",
"aceite": "oil",
"vinagre": "vinegar",
"miel": "honey",
"café": "coffee",
"té": "tea",
"cacao": "cocoa",
"atún": "tuna",
"sardina": "sardine",
"sopa": "soup",
"mostaza": "mustard",
"azafrán": "saffron",
"canela": "cinnamon",
"clavo": "clove",
"comino": "cumin",
"curry": "curry",
"curcuma": "turmeric",
"pimienta": "pepper",
"sal": "salt",
"leche": "milk",
"queso": "cheese",
"mantequilla": "butter",
"yogur": "yogurt",
"huevo": "egg",
"nata": "cream",
"cuajada": "curd",
"queso crema": "cream cheese",
"yogurth": "yogurt",
"lentejas": "lentils"
}